export const newProperty = [
    {
        id: 1,
        name: 'Beautiful House',
        latitude: 34.053691,
        longitude: -118.242766,
        address: '123 Main St',
        city: 'Jaipur',
        state: 'India',
        price: 500000,
        imageUrl: 'https://is1-2.housingcdn.com/4f2250e8/e5ea5a06784f3de420dc8fbac7f0ed59/v5/large.jpg.webp',
        description: 'A charming house with a lovely garden in a quiet neighborhood.',
        type: 'House',
        status: 'For Sale',
    },
    {
        id: 2,
        name: 'Cozy Apartment',
        latitude: 37.0902,
        longitude: -95.7129,
        address: '456 Oak St',
        city: 'San Francisco',
        state: 'CA',
        price: 250000,
        imageUrl: 'https://is1-3.housingcdn.com/4f2250e8/f4cc5ceeae3b43e4a56995e80d36e9f5/v5/large/delta_vaswani_brentwood-whitefield-bengaluru-delta_spaces.jpg.webp',
        description: 'A cozy apartment with a great view of the city.',
        type: 'Apartment',
        status: 'For Rent',
    },
    {
        id: 3,
        name: 'Los Angeles International Airport ',
        latitude: 56.1304,
        longitude: -106.3468,
        address: 'los angles',
        city: 'los angles',
        state: 'something',
        price: 100,
        imageUrl: 'https://is1-3.housingcdn.com/4f2250e8/15ae065e483d22ae0e67222b87179c58/v0/large/sumadhura_eden_garden-whitefield-bengaluru-sumadhura_infracon_pvt_ltd.jpeg.webp',
        description: 'A cozy apartment with a great view of the city.',
        type: 'Apartment',
        status: 'For Rent',
    },
    {
        id: 4,
        name: 'Los Angeles International Airport ',
        latitude: 23.6345,
        longitude: -102.5528,
        address: 'los angles',
        city: 'los angles',
        state: 'something',
        price: 100,
        imageUrl: 'https://is1-3.housingcdn.com/4f2250e8/15ae065e483d22ae0e67222b87179c58/v0/large/sumadhura_eden_garden-whitefield-bengaluru-sumadhura_infracon_pvt_ltd.jpeg.webp',
        description: 'A cozy apartment with a great view of the city.',
        type: 'Apartment',
        status: 'For Rent',
    },
    {
        id: 5,
        name: 'Washington Property',
        latitude: 38.9072,
        longitude: -77.0369,
        address: 'Washington, D.C.',
        city: 'Washington',
        state: 'D.C.',
        price: 200,
        imageUrl: 'https://is1-2.housingcdn.com/4f2250e8/99042cd854d748bbef0099efd81acb24/v0/medium.jpeg.webp',
        description: 'A beautiful property in Washington.',
        type: 'House',
        status: 'For Sale'
    },
    {
        id: 6,
        name: 'New York Property',
        latitude: 40.7128,
        longitude: -74.0060,
        address: 'New York City',
        city: 'New York',
        state: 'NY',
        price: 300,
        imageUrl: 'https://is1-2.housingcdn.com/012c1500/f09c54660bb8da20bf5ebb128d2aa31e/v0/fs.jpeg.webp',
        description: 'A modern apartment in the heart of New York City.',
        type: 'Apartment',
        status: 'For Rent'
    },
    {
        id: 7,
        name: 'Colombia Property',
        latitude: 4.5709,
        longitude: -74.2973,
        address: 'Bogotá',
        city: 'Bogotá',
        state: 'Cundinamarca',
        price: 150,
        imageUrl: 'https://is1-3.housingcdn.com/4f2250e8/d89dc100ee62ca14c02bd357c7b8cff4/v0/large/kesar_gateway-kamptee-nagpur-kesar_lands_private_limited.jpeg.webp',
        description: 'A cozy property in the capital city of Colombia.',
        type: 'House',
        status: 'For Sale'
    },
    {
        id: 8,
        name: 'Calgary Property',
        latitude: 51.0447,
        longitude: -114.0719,
        address: 'Calgary',
        city: 'Calgary',
        state: 'Alberta',
        price: 200,
        imageUrl: 'https://is1-3.housingcdn.com/4f2250e8/29aaa5f5d8c3656bc315579600694769/v0/fs/leverage_green_heights-shankarpur_1-nagpur-bhumesh_realtors.jpeg.webp',
        description: 'A beautiful property in the city of Calgary.',
        type: 'Apartment',
        status: 'For Rent'
    },
    {
        id: 9,
        name: 'Cuba Property',
        latitude: 21.5218,
        longitude: -77.7812,
        address: 'Havana',
        city: 'Havana',
        state: 'La Habana',
        price: 180,
        imageUrl: 'https://is1-3.housingcdn.com/012c1500/ddd80eafa0f365b1f289de619f692cd5/v0/fs.jpeg.webp',
        description: 'A charming property in the vibrant city of Havana, Cuba.',
        type: 'Villa',
        status: 'For Rent'
    },
    {
        id: 10,
        name: 'Vancouver Property',
        latitude: 49.2827,
        longitude: -123.1207,
        address: 'Vancouver',
        city: 'Vancouver',
        state: 'British Columbia',
        price: 200,
        imageUrl: 'https://is1-2.housingcdn.com/012c1500/83a6fc1887ae133b6ec5fdaa096b2f4d/v0/fs.jpeg.webp',
        description: 'A stunning property in the beautiful city of Vancouver, Canada.',
        type: 'Apartment',
        status: 'For Sale'
    },
    {
        id: 11,
        name: 'San Francisco Property',
        latitude: 37.7749,
        longitude: -122.4194,
        address: 'San Francisco',
        city: 'San Francisco',
        state: 'California',
        price: 250,
        imageUrl: 'https://is1-3.housingcdn.com/4f2250e8/629b1dfa79b915d54647302e836f7353/v0/fs/godrej_athena-indira_nagar-bengaluru-godrej_properties_ltd.jpeg.webp',
        description: 'A modern property in the vibrant city of San Francisco.',
        type: 'Condo',
        status: 'For Rent'
    },
    {
        id: 12,
        name: 'Brazil Property',
        latitude: -14.2350,
        longitude: -51.9253,
        address: 'Brazil',
        city: 'Rio de Janeiro',
        state: 'Rio de Janeiro',
        price: 180,
        imageUrl: 'https://is1-2.housingcdn.com/012c1500/f9e5d151a5aea7fb2af0009d2008b2c1/v0/fs.jpeg.webp',
        description: 'A beautiful property in the lively city of Rio de Janeiro, Brazil.',
        type: 'Villa',
        status: 'For Sale'
    },
    {
        id: 13,
        name: 'Costa Rica Property',
        latitude: 9.7489,
        longitude: -83.7534,
        address: 'Costa Rica',
        city: 'San José',
        state: 'San José',
        price: 200,
        imageUrl: 'https://img.staticmb.com/mbphoto/property/cropped_images/2022/May/21/Photo_h0_w320/60031377_20_PropertyImage1653141217671_0_320.jpg',
        description: 'A tropical property in the capital city of San José, Costa Rica.',
        type: 'Beach House',
        status: 'For Rent'
    },
    {
        id: 14,
        name: 'Guyana Property',
        latitude: 4.8604,
        longitude: -58.9302,
        address: 'Guyana',
        city: 'Georgetown',
        state: 'Demerara-Mahaica',
        price: 120,
        imageUrl: 'https://img.staticmb.com/mbimages/project/Photo_h0_w320/2022/04/29/Project-Photo-6-Saishakti-Symphony-Hyderabad-5118007_949_2000_0_320.jpg',
        description: 'A cozy property in the capital city of Georgetown, Guyana.',
        type: 'Apartment',
        status: 'For Sale'
    },
    {
        id: 15,
        name: 'Argentina Property',
        latitude: -34.6037,
        longitude: -58.3816,
        address: 'Argentina',
        city: 'Buenos Aires',
        state: 'Buenos Aires',
        price: 220,
        imageUrl: 'https://img.staticmb.com/mbphoto/property/cropped_images/2022/May/21/Photo_h0_w320/60031377_3_PropertyImage1653140973275_0_320.jpg',
        description: 'A modern property in the vibrant city of Buenos Aires, Argentina.',
        type: 'Penthouse',
        status: 'For Rent'
    },
    {
        id: 16,
        name: 'United Kingdom Property',
        latitude: 51.5074,
        longitude: -0.1278,
        address: 'United Kingdom',
        city: 'London',
        state: 'England',
        price: 250,
        imageUrl: 'https://img.staticmb.com/mbimages/project/Photo_h0_w320/2022/07/27/Project-Photo-41-DSR-Highland-Greenz-Bangalore-5333811_1200_1600_0_320.jpg',
        description: 'A charming property in the heart of London, United Kingdom.',
        type: 'Townhouse',
        status: 'For Sale'
    },
    {
        id: 17,
        name: 'France Property',
        latitude: 48.8566,
        longitude: 2.3522,
        address: 'France',
        city: 'Paris',
        state: 'Île-de-France',
        price: 280,
        imageUrl: 'https://img.staticmb.com/mbimages/project/Photo_h0_w320/2022/07/27/Project-Photo-24-DSR-Highland-Greenz-Bangalore-5333811_1200_1600_0_320.jpg',
        description: 'An elegant property in the romantic city of Paris, France.',
        type: 'Mansion',
        status: 'For Rent'
    },
    {
        id: 18,
        name: 'Peru Property',
        latitude: -12.0464,
        longitude: -77.0428,
        address: 'Peru',
        city: 'Lima',
        state: 'Lima',
        price: 150,
        imageUrl: 'https://img.staticmb.com/mbimages/project/Photo_h0_w320/2022/07/27/Project-Photo-27-DSR-Highland-Greenz-Bangalore-5333811_1200_1600_0_320.jpg',
        description: 'A modern property in the bustling city of Lima, Peru.',
        type: 'Condo',
        status: 'For Sale'
    },
    {
        id: 19,
        name: 'Iceland Property',
        latitude: 64.9631,
        longitude: -19.0208,
        address: 'Iceland',
        city: 'Reykjavik',
        state: 'Capital Region',
        price: 200,
        imageUrl: 'https://img.staticmb.com/mbimages/project/Photo_h0_w320/2022/07/27/Project-Photo-31-DSR-Highland-Greenz-Bangalore-5333811_1200_1600_0_320.jpg',
        description: 'A cozy property in the picturesque city of Reykjavik, Iceland.',
        type: 'Cottage',
        status: 'For Rent'
    },
    {
        id: 20,
        name: 'Greenland Property',
        latitude: 64.1814,
        longitude: -51.6941,
        address: 'Greenland',
        city: 'Nuuk',
        state: 'Sermersooq',
        price: 180,
        imageUrl: 'https://img.staticmb.com/mbimages/project/Photo_h0_w320/2022/07/27/Project-Photo-35-DSR-Highland-Greenz-Bangalore-5333811_1200_1600_0_320.jpg',
        description: 'A secluded property in the capital city of Nuuk, Greenland.',
        type: 'Chalet',
        status: 'For Sale'
    }


];